### ISSUE TITLE
JavaCV-android-example, failed to record, unable to open prcui-config.jar

### ISSUE THREAD

**Issue by bibounet** [bytedeco/sample-projects#10]
One I push the "start" recording button, I got these errors on my logcat : 
I didn't change anything on the code, error happens on RecordActivity l216 : 

`recorder = new FFmpegFrameRecorder(ffmpeg_link, imageWidth, imageHeight, 1);`

logcat : 

> Unable to open '/system/framework/prcui-config.jar': No such file or directory
> W/art: Failed to open zip archive '/system/framework/prcui-config.jar': I/O Error
> W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -13: Could not open 'null'
> W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:784)
> W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:351)
> W/System.err:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:236)
> W/System.err:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:316)
> W/System.err:     at android.view.View.performClick(View.java:5207)
> W/System.err:     at android.view.View$PerformClick.run(View.java:21168)
> W/System.err:     at android.os.Handler.handleCallback(Handler.java:746)
> W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
> W/System.err:     at android.os.Looper.loop(Looper.java:148)
> W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5459)
> W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
> W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
> W/RecordActivity: Start Button Pushed
> I/Choreographer: Skipped 59 frames!  The application may be doing too much work on its main thread.

**Comment by saudet** [comment]
Could you also provide the messages you get in the log?

**Comment by bibounet** [comment]
Thank you for your help!
The complete log (from logcat) is in the attached file.
my device is a motoG5 with android 7.0

**Comment by saudet** [comment]
That doesn't include the log of FFmpeg. Please call FFmpegLogCallback.set() somewhere before that line.

**Comment by bibounet** [comment]
Sorry to reply late, new log : [motoG5-log.txt](https://github.com/bytedeco/sample-projects/files/878188/motoG5-log.txt)

**Comment by saudet** [comment]
Thanks! `Unknown: none (mpeg4)`: You'll need to specify valid codecs and such.

**Comment by bibounet** [comment]
in fact writing (stream.mp4) on external storage do not work on any devices, that was the error (npe).
moving the destination of the output (stream.mp4) on internal storage solve the crash.

But now my stream.mp4 is unreadable...  and has always a size of ~250B ..
even if I set my codecs to : `recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);`

As it's not the frst subject of this issue would you like me to open a stackoverflow thread? or another issue? in any case thank you for your help

**Comment by saudet** [comment]
You'll need to call `recorder.stop()` somewhere if you want to get a valid file.

**Comment by saudet** [comment]
And please use the latest version of JavaCV 1.3.2. You're using an old version.

**Comment by bibounet** [comment]
Hi, I updated from 1.3.1 to 1.3.2, and I'm calling recorder.stop() (as it's implemented in the android sample project) but I still have an empty video ~250B ...

**Comment by saudet** [comment]
Could you show an updated version of the log as well?

**Comment by bibounet** [comment]
thank you for your help... here is the new log [motoG5-log.txt](https://github.com/bytedeco/sample-projects/files/905200/motoG5-log.txt)

**Comment by saudet** [comment]
It's only recording for less than 1second. It probably doesn't have any time to record anything. Try to record for a longer period of time.

**Comment by bibounet** [comment]
Same mp4 file size with 15 secondes or more... 
[motoG5-log.txt](https://github.com/bytedeco/sample-projects/files/913186/motoG5-log.txt)

**Comment by saudet** [comment]
We could try to increase the verbosity of the log...

**Comment by bibounet** [comment]
How can I change the log level with FFmpegLogCallback?

**Comment by saudet** [comment]
Try av_set_log_level( AV_LOG_DEBUG)
