### ISSUE TITLE
The video is not playing in vidoe stabilization

### ISSUE THREAD

**Issue by Nischitha-S** [bytedeco/sample-projects#17]
Hi,
   Iam getting this errror .Please let me know that how can i overcome this 

W/System.err: org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -2: Could not open input "/storage/emulated/0/media/v4.avi". (Has setFormat() been called?)

**Comment by saudet** [comment]
Errno 2 just means the file doesn't exist. Try to open an existing file.

**Comment by Nischitha-S** [comment]
Its opening in the mobile separetly.But when i try to execute the code its
not opening instead it showing the error
 W/linker: libjniavutil.so: unused DT entry: type 0xf arg 0x18b9d
with a blank screen

Thanks
S.Nischitha

**Comment by saudet** [comment]
I don't understand your English, you'll need to make sense if you want some help.

**Comment by Nischitha-S** [comment]
When i open the video separately  it is playing, but when i give the same video as input its showing that
unused DT entry: type 0xf arg 0x18b9d

**Comment by saudet** [comment]
You're still not making any sense. Does it play? Or does it not play?

**Comment by Nischitha-S** [comment]
No its not displaying

**Comment by saudet** [comment]
I told you the error means the file does not exist. You'll need first a file to play!

**Comment by Nischitha-S** [comment]
ok thank you sir
