### ISSUE TITLE
Make a mean.binaryproto from java (Question)

### ISSUE THREAD

**Issue by OleksandrGrument** [bytedeco/sample-projects#28]
Hello, i'm trying to implement in java deepdream notebook from python  
[https://github.com/google/deepdream/blob/master/dream.ipynb](url)

in  python there are code that generating mean.binaryproto from values.

`mean = np.float32([104.0, 116.0, 122.0]), # ImageNet mean, training set`

I have add a library java variant of Nyphy called Nd4j.

Tryed to generate the mean file with code bellow.

      `     
        String meanFile = caffeConfigRoot + "mean.binaryproto";
        
        double[] meanTrainingSet = {104.0, 116.0, 122.0};

        INDArray indArray = Nd4j.create(meanTrainingSet);

        try (DataOutputStream dos = new DataOutputStream(new FileOutputStream(new File(meanFile)))){

            Nd4j.write(indArray, dos);

        }`

And i'm getting the error.

`[blob.cpp:496] Check failed: count_ == proto.data_size() (1 vs. 0) `

in this piece of code 

` 
    
    BlobProto blobProto = new BlobProto();

    ReadProtoFromBinaryFileOrDie(meanFile, blobProto);

    FloatBlob meanBlob = new FloatBlob();

    meanBlob.FromProto(blobProto);
`

Maybe is there some code how to generate this mean file from java or the problem not in mean file and it correct.

Anyway I'm trying to find a solution but there are a few information about this. Any help would be appreciated. Thank you;

**Comment by saudet** [comment]
It would probably be easier to find a way to write it with Caffe. We could then be sure the data format is compatible. Any ideas @cypof?

**Comment by saudet** [comment]
Strange, would you know @Undin ?

**Comment by Undin** [comment]
I don't really know but this sample is just java version of the original sample. And it has [this check](https://github.com/BVLC/caffe/blob/master/examples/cpp_classification/classification.cpp#L127-L128) too.
