### ISSUE TITLE
result isn't correct..

### ISSUE THREAD

**Issue by malikdawar** [bytedeco/sample-projects#37]
Hi! this project is really helpful, thanks for the efforts. But somehow the result isn't accurate, it is also authenticating otherwise persons. Would you pl like to guide me how to make it more reliable and secure.
Bundle of thanks in advance.

**Comment by saudet** [comment]
Please follow the tutorial! https://docs.opencv.org/3.4.1/da/d60/tutorial_face_main.html

**Comment by saudet** [comment]
Or please clarify what is your question is about, thanks!
