### ISSUE TITLE
taking 20 sec to load javacv  in OpenCvRecognizeActivity

### ISSUE THREAD

**Issue by pafzalkhan** [bytedeco/sample-projects#45]
Is there any way to reduce loading time of JavaCV, native libraries of OpenCV.

**Comment by saudet** [comment]
It might take a few seconds to load the first time only. It will load quickly from cache after.

**Comment by saudet** [comment]
There are also apparently some issues on Android that I am unable to reproduce thus unable to fix. If you would like to make a contribution, that would be great! Please see details on how you could help at https://github.com/bytedeco/javacpp/issues/287.
