### ISSUE TITLE
 error: ‘MultiplyDemo’ has not been declared

### ISSUE THREAD

**Issue by nitin2212** [bytedeco/sample-projects#48]
In the example : https://github.com/bytedeco/sample-projects/tree/master/javacpp-mvn-simple-demo

**When I modify the class by extending Pointer, it gives error** : 

**error: ‘MultiplyDemo’ has not been declared**

Why ?

**Comment by saudet** [comment]
Because there is no C++ class named `MultiplyDemo`. You'll need to create one for this to work.

**Comment by nitin2212** [comment]
Alright. I got it ! Thank you.
