### ISSUE TITLE
JavaCV-android-example doesn't record anything on some devices

### ISSUE THREAD

**Issue by Denis1986** [bytedeco/sample-projects#5]
I have downloaded the last version of JavaCV-android-example, built it in Android Studio 1.5.1 and started on Samsung Galaxy S6 Edge with Android 5.1.1. I clicked "Start" button, then after ~30 seconds "Stop" button. After all output file size was 44 bytes. I suppose that it is some kind of metadata. I added more logs to RecordActivity: on recorder.record() and recorder.recordSample() calls. These methods were called many times as expected. But why no data were written to output file "stream.mp4"?

**Comment by saudet** [comment]
I don't know, let's check the Android log!

**Comment by saudet** [comment]
Also, please try to call `FFmpegLogCallback.set()` during initialization to get more messages in the log. Let me know what you get, thanks!

**Comment by Denis1986** [comment]
As a result, problem was on my side. Changes of files, stored on the internal (emulated) sd card, are sometimes visible to PC and sometimes not (in this case it is necessary to reconnect phone to USB). This unpredictable behaviour led me to the wrong conclusions about JavaCV-android-example, because I didn't see changes in output video file. So issue does not exist.
