### ISSUE TITLE
build error on AndroidStudio 4.1

### ISSUE THREAD

**Issue by weikaiyun** [bytedeco/sample-projects#53]
javacpp-android-gradle build failed on AndroidStudio 4.1

**Comment by saudet** [comment]
That sample needs to be updated with Gradle JavaCPP: https://github.com/bytedeco/gradle-javacpp

**Comment by weikaiyun** [comment]
I need an Android application example, not just java demo

**Comment by saudet** [comment]
Please consider making a contribution! Either in code or in cash:  https://xscode.com/bytedeco/gradle-javacpp

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/gradle-javacpp/issues/5

**Comment by saudet** [comment]
Thanks to @iuliuh, we now have this new sample project:
https://github.com/bytedeco/sample-projects/tree/master/gradle-javacpp-android
Along with instructions for integration with Android Studio. Enjoy!
